import { EsdsIconAngleLeft } from './dist/EsdsIconAngleLeft.svg.js';
import { EsdsIconAngleRight } from './dist/EsdsIconAngleRight.svg.js';
import { EsdsIconBars } from './dist/EsdsIconBars.svg.js';
import { EsdsIconCaretDown } from './dist/EsdsIconCaretDown.svg.js';
import { EsdsIconCaretUp } from './dist/EsdsIconCaretUp.svg.js';
import { EsdsIconCheck } from './dist/EsdsIconCheck.svg.js';
import { EsdsIconEightshapesLogo } from './dist/EsdsIconEightshapesLogo.svg.js';
import { EsdsIconEightshapesMark } from './dist/EsdsIconEightshapesMark.svg.js';
import { EsdsIconLinkedin } from './dist/EsdsIconLinkedin.svg.js';
import { EsdsIconMedium } from './dist/EsdsIconMedium.svg.js';
import { EsdsIconMinus } from './dist/EsdsIconMinus.svg.js';
import { EsdsIconParticipants } from './dist/EsdsIconParticipants.svg.js';
import { EsdsIconStopwatch } from './dist/EsdsIconStopwatch.svg.js';
import { EsdsIconTwitter } from './dist/EsdsIconTwitter.svg.js';

export { EsdsIconAngleLeft };
export { EsdsIconAngleRight };
export { EsdsIconBars };
export { EsdsIconCaretDown };
export { EsdsIconCaretUp };
export { EsdsIconCheck };
export { EsdsIconEightshapesLogo };
export { EsdsIconEightshapesMark };
export { EsdsIconLinkedin };
export { EsdsIconMedium };
export { EsdsIconMinus };
export { EsdsIconParticipants };
export { EsdsIconStopwatch };
export { EsdsIconTwitter };
